services:
  postgres:
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_DB=url-shorten-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  pg_data:
    driver: local